// Slices the three hero sheets (Saka / Kara / Zell, in Assets/heroes/) into
// per-state PNGs the engine can load:
//
//   public/assets/sprites/heroes/<id>/idle.png   (multi-frame strip, side-facing)
//   public/assets/sprites/heroes/<id>/walk.png   (multi-frame strip, side-facing)
//   public/assets/sprites/heroes/<id>/front.png  (single frame, facing camera)
//   public/assets/sprites/heroes/<id>/back.png   (single frame, away from camera)
//
// The sheets are project-owned (AI-generated by the project author) — no
// third-party license; see CREDITS.txt.
//
// Layout is auto-detected: each named animation lives on a horizontal "strip"
// separated by gaps of background, and we find strips by scanning pixel rows
// for non-background content within column bands. This is robust to small
// per-sheet variation in row positions.
//
// Subsequent milestones will extend this to attack/skill strips per character.
// Run: npm run heroes

import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "Assets", "heroes");
const OUT = join(root, "public", "assets", "sprites", "heroes");

const HEROES = ["saka", "kara", "zell"];

// Source sheets are JPEGs with a solid near-black background (RGB ~ 0..10 per
// channel). Convert that to transparency in two passes:
//   1. THRESHOLD: any pixel with all three channels below CHROMA_T becomes
//      alpha = 0. Threshold is deliberately low so we don't punch holes in
//      dark armor / hair (those pixels typically have at least one channel > 14).
//   2. DENOISE: JPEG compression leaves scattered slightly-brighter specks
//      around the figure that the threshold misses. We strip any opaque pixel
//      that has too few opaque neighbors in its 3x3 — i.e. an isolated speck —
//      while leaving connected figure pixels intact.
const CHROMA_T = 14;
const DENOISE_MIN_NEIGHBORS = 3;

// The basic-attack row in each sheet is a flipbook of ~6 poses whose per-frame
// widths vary wildly: the first few are the figure winding up / swinging (body
// only) and the later ones tack on a wide slash-arc FX trail. Slicing that row
// into N equal cells therefore crops ACROSS pose boundaries and produces a
// ghosted smear. Instead we detect the individual pose clusters, keep the first
// ATTACK_FRAMES body-only swing poses (dropping the FX trails — the battle
// engine renders its own slash/skill FX), and re-pack them into a clean,
// uniform-cell strip. ATTACK_FRAMES is fixed so the engine can step 1/N without
// a per-hero manifest; keep it in sync with HERO_ATTACK_FRAMES in Battle3D.ts.
const ATTACK_FRAMES = 3;

// IDLE / WALK rows have the same problem as the attack row, just subtler: the
// per-pose bounding boxes vary (~52-66px) and sit on a slightly uneven pitch,
// so cropping the whole row tight and letting the engine slice it into N equal
// cells lands every cell a few px off the pose — the figure ghosts in slivers
// of its neighbours and shimmies left/right as it cycles. We re-pack these into
// clean uniform cells exactly like the attack row. Keep in sync with HERO_FRAMES
// in World3D.ts (the engine steps idle/walk at 1/HERO_FRAMES).
const IDLE_WALK_FRAMES = 9;

// Apply the chroma key to a buffer of raw RGBA pixels in-place.
function chromaKey(rgba) {
  for (let i = 0; i < rgba.length; i += 4) {
    if (rgba[i] < CHROMA_T && rgba[i + 1] < CHROMA_T && rgba[i + 2] < CHROMA_T) {
      rgba[i + 3] = 0;
    }
  }
}

// Strip isolated opaque specks: any opaque pixel with fewer than
// DENOISE_MIN_NEIGHBORS opaque neighbors in its 3x3 gets alpha = 0. Uses a
// snapshot of the alpha channel so the test is on the pre-strip state (no
// cascading; one pass).
function denoiseAlpha(rgba, w, h) {
  const alpha = new Uint8Array(w * h);
  for (let i = 0, j = 0; i < rgba.length; i += 4, j++) alpha[j] = rgba[i + 3] > 0 ? 1 : 0;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const idx = y * w + x;
      if (!alpha[idx]) continue;
      let n = 0;
      for (let dy = -1; dy <= 1; dy++) {
        const yy = y + dy; if (yy < 0 || yy >= h) continue;
        for (let dx = -1; dx <= 1; dx++) {
          if (dx === 0 && dy === 0) continue;
          const xx = x + dx; if (xx < 0 || xx >= w) continue;
          if (alpha[yy * w + xx]) n++;
        }
      }
      if (n < DENOISE_MIN_NEIGHBORS) rgba[idx * 4 + 3] = 0;
    }
  }
}

// Wrap a sharp pipeline so the output buffer has the background keyed out
// (threshold + isolated-speck denoise).
async function keyedPng(pipeline) {
  const { data, info } = await pipeline.ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  chromaKey(data);
  denoiseAlpha(data, info.width, info.height);
  return sharp(data, { raw: { width: info.width, height: info.height, channels: 4 } }).png().toBuffer();
}

// Column bands for content scanning. The middle column holds IDLE/WALK/etc.;
// the right column holds the FACING DIRECTION row + victory/hit/etc.
//
// RIGHT_X starts at 1040 (not 1100): the FRONT-facing figure of the FACING
// DIRECTION row sits flush against the left edge of the right column and its
// body extends to ~x1060-1064. Starting the scan at 1100 clipped the front
// figure to a <24px sliver that got rejected, which shifted every facing label
// one slot left (front.png got the BACK pose, back.png got the LEFT pose, ...).
// 1040 captures the whole front figure while staying clear of the middle
// column (ends 1000) and any panel grid-lines (zell has borders at x1005/1020).
const MIDDLE_X = [240, 1000];
const RIGHT_X = [1040, 1500];

// Scan a vertical band for horizontal "content strips" (rows with non-black
// pixel mass). Returns [{y0, y1, h}] for each strip taller than minH.
function scanBands(data, W, H, x0, x1, minH = 16, lumaT = 32, fracT = 0.05) {
  const cols = x1 - x0;
  const rowCount = new Array(H).fill(0);
  for (let y = 0; y < H; y++) {
    let n = 0;
    for (let x = x0; x < x1; x++) {
      const i = (y * W + x) * 4;
      const l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
      if (l > lumaT) n++;
    }
    rowCount[y] = n;
  }
  const T = Math.round(cols * fracT);
  const bands = [];
  let inB = false, s = 0;
  for (let y = 0; y < H; y++) {
    const hot = rowCount[y] > T;
    if (hot && !inB) { inB = true; s = y; }
    else if (!hot && inB) { bands.push({ y0: s, y1: y - 1, h: y - s }); inB = false; }
  }
  if (inB) bands.push({ y0: s, y1: H - 1, h: H - s });
  return bands.filter(b => b.h >= minH);
}

// Within a horizontal strip [y0..y1] over the middle column, find the X content
// range so the saved strip is tight-cropped horizontally as well.
function scanStripX(data, W, H, x0, x1, y0, y1, lumaT = 32, fracT = 0.04) {
  const rows = y1 - y0 + 1;
  const colCount = new Array(W).fill(0);
  for (let x = 0; x < W; x++) {
    let n = 0;
    for (let y = y0; y <= y1; y++) {
      const i = (y * W + x) * 4;
      const l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
      if (l > lumaT) n++;
    }
    colCount[x] = n;
  }
  const T = Math.max(1, Math.round(rows * fracT));
  let cs = -1, ce = -1;
  for (let x = x0; x < x1; x++) if (colCount[x] > T) { cs = x; break; }
  for (let x = x1 - 1; x >= x0; x--) if (colCount[x] > T) { ce = x; break; }
  return cs >= 0 && ce > cs ? { x0: cs, x1: ce } : null;
}

// Within the FACING DIRECTION strip (FRONT / BACK / LEFT / RIGHT) split the row
// into individual frames by finding the 4 distinct column clusters of content.
function findFacingFrames(data, W, H, x0, x1, y0, y1) {
  const rows = y1 - y0 + 1;
  const colCount = new Array(W).fill(0);
  for (let x = x0; x < x1; x++) {
    let n = 0;
    for (let y = y0; y <= y1; y++) {
      const i = (y * W + x) * 4;
      const l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
      if (l > 32) n++;
    }
    colCount[x] = n;
  }
  const T = Math.max(1, Math.round(rows * 0.06));
  // group consecutive "hot" cols into clusters
  const clusters = [];
  let inC = false, cs = 0;
  for (let x = x0; x < x1; x++) {
    const hot = colCount[x] > T;
    if (hot && !inC) { inC = true; cs = x; }
    else if (!hot && inC) { clusters.push({ x0: cs, x1: x - 1 }); inC = false; }
  }
  if (inC) clusters.push({ x0: cs, x1: x1 - 1 });
  // merge clusters separated by tiny gaps (the figure has limbs that may break)
  const merged = [];
  for (const c of clusters) {
    const last = merged[merged.length - 1];
    if (last && c.x0 - last.x1 < 8) last.x1 = c.x1;
    else merged.push({ ...c });
  }
  // Reject sliver-thin clusters (panel borders / label artifacts) and keep the
  // 4 leftmost real ones — order then naturally maps to FRONT/BACK/LEFT/RIGHT.
  return merged.filter(c => c.x1 - c.x0 >= 24).slice(0, 4);
}

// Split a horizontal strip into column clusters (contiguous runs of "hot" cols),
// merging runs separated by gaps smaller than `mergeGap` (so a held weapon /
// broken limb stays attached to its body). Returns [{x0, x1}] left-to-right.
function columnClusters(data, W, x0, x1, y0, y1, mergeGap = 16) {
  const rows = y1 - y0 + 1;
  const colCount = new Array(W).fill(0);
  for (let x = x0; x < x1; x++) {
    let n = 0;
    for (let y = y0; y <= y1; y++) {
      const i = (y * W + x) * 4;
      const l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
      if (l > 32) n++;
    }
    colCount[x] = n;
  }
  const T = Math.max(1, Math.round(rows * 0.06));
  const runs = [];
  let inC = false, cs = 0;
  for (let x = x0; x < x1; x++) {
    const hot = colCount[x] > T;
    if (hot && !inC) { inC = true; cs = x; }
    else if (!hot && inC) { runs.push({ x0: cs, x1: x - 1 }); inC = false; }
  }
  if (inC) runs.push({ x0: cs, x1: x1 - 1 });
  const merged = [];
  for (const c of runs) {
    const last = merged[merged.length - 1];
    if (last && c.x0 - last.x1 < mergeGap) last.x1 = c.x1;
    else merged.push({ ...c });
  }
  return merged;
}

// Slice the basic-attack row into a clean uniform strip of ATTACK_FRAMES body
// poses. Picks the first body-sized clusters (width in [minW, maxW]) — these
// are the swing poses before the wide FX-arc frames — and centers each one,
// bottom-aligned, in an identically sized cell so the engine can flipbook them
// at 1/ATTACK_FRAMES without the figure drifting or squishing. Returns the
// output strip buffer + its dimensions, or null if no body clusters are found.
async function packAttackStrip(src, data, W, H, band, unifyH, pad) {
  const minW = 30, maxW = 130;
  const all = columnClusters(data, W, MIDDLE_X[0], MIDDLE_X[1], band.y0, band.y1, 16);
  let body = all.filter(c => { const w = c.x1 - c.x0; return w >= minW && w <= maxW; });
  if (body.length === 0) return null;
  body = body.slice(0, ATTACK_FRAMES);
  // pad out to ATTACK_FRAMES by repeating the last pose so the strip is uniform
  while (body.length < ATTACK_FRAMES) body.push(body[body.length - 1]);
  const stripH = band.y1 - band.y0 + 1;
  // crop each pose tightly, keyed
  const crops = [];
  for (const c of body) {
    const w = c.x1 - c.x0 + 1;
    const buf = await keyedPng(sharp(src).extract({ left: c.x0, top: band.y0, width: w, height: stripH }));
    crops.push({ buf, w });
  }
  const cellW = Math.max(...crops.map(c => c.w)) + pad * 2;
  const topPad = unifyH - stripH - pad; // bottom-aligned (feet on the shared baseline)
  const layers = crops.map((c, i) => ({
    input: c.buf,
    left: i * cellW + Math.round((cellW - c.w) / 2), // center the figure in its cell
    top: topPad,
  }));
  const out = await sharp({ create: { width: cellW * ATTACK_FRAMES, height: unifyH, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite(layers).png().toBuffer();
  return { buf: out, w: cellW * ATTACK_FRAMES, h: unifyH, frames: ATTACK_FRAMES };
}

// Re-pack an IDLE / WALK row into a clean strip of exactly `frames` uniform
// cells. Detects the individual pose clusters (small merge gap so a held weapon
// / extended limb stays attached, but the ~20px gaps between poses keep poses
// separate), drops sliver clusters (the 1-2px denoise speck at the row edge,
// panel borders), splits any cluster wide enough to be two poses fused at a
// near-zero gap, then crops each pose tightly and centers it bottom-aligned in
// an identically sized cell. The result slices perfectly at 1/frames with no
// drift or neighbour-bleed. Returns the strip buffer + dimensions, or null.
async function packUniformStrip(src, data, W, H, band, unifyH, pad, frames) {
  const stripH = band.y1 - band.y0 + 1;
  let poses = columnClusters(data, W, MIDDLE_X[0], MIDDLE_X[1], band.y0, band.y1, 10);
  // drop slivers (denoise specks, panel grid-lines): real poses are >= 24px wide
  poses = poses.filter(c => c.x1 - c.x0 + 1 >= 24);
  if (poses.length === 0) return null;
  // split over-wide clusters: two poses fused at a sub-merge-gap separation read
  // as one blob. Use the median width to estimate how many poses a cluster holds.
  const sorted = poses.map(c => c.x1 - c.x0 + 1).sort((a, b) => a - b);
  const median = sorted[Math.floor(sorted.length / 2)];
  const split = [];
  for (const c of poses) {
    const w = c.x1 - c.x0 + 1;
    const n = Math.max(1, Math.round(w / median));
    if (n <= 1) { split.push(c); continue; }
    const sw = w / n;
    for (let k = 0; k < n; k++) split.push({ x0: Math.round(c.x0 + k * sw), x1: Math.round(c.x0 + (k + 1) * sw) - 1 });
  }
  poses = split.slice(0, frames);
  // pad to `frames` by repeating the last pose so the cell pitch stays uniform
  while (poses.length < frames) poses.push(poses[poses.length - 1]);
  const crops = [];
  for (const c of poses) {
    const w = c.x1 - c.x0 + 1;
    const buf = await keyedPng(sharp(src).extract({ left: c.x0, top: band.y0, width: w, height: stripH }));
    crops.push({ buf, w });
  }
  const cellW = Math.max(...crops.map(c => c.w)) + pad * 2;
  const topPad = unifyH - stripH - pad; // bottom-aligned (feet on the shared baseline)
  const layers = crops.map((c, i) => ({
    input: c.buf,
    left: i * cellW + Math.round((cellW - c.w) / 2), // center the figure in its cell
    top: topPad,
  }));
  const out = await sharp({ create: { width: cellW * frames, height: unifyH, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite(layers).png().toBuffer();
  return { buf: out, w: cellW * frames, h: unifyH, frames };
}

async function processHero(id) {
  const src = join(SRC, `${id}.png`);
  const { data, info } = await sharp(src).raw().ensureAlpha().toBuffer({ resolveWithObject: true });
  const W = info.width, H = info.height;
  const outDir = join(OUT, id);
  await mkdir(outDir, { recursive: true });

  // Middle column band order (constant across the template):
  //   0: IDLE          1: WALK          2: RUN           3: JUMP* / DASH
  //   ...
  //   The BASIC ATTACK row is the first band of the ATTACKS section, which sits
  //   right after the locomotion rows. The exact index depends on whether the
  //   character has JUMP — Saka/Zell have JUMP (so attack-basic = band 5);
  //   Kara doesn't have a JUMP row (so attack-basic = band 4).
  const attackBandIdx = id === "kara" ? 4 : 5;
  const midBands = scanBands(data, W, H, MIDDLE_X[0], MIDDLE_X[1]);
  if (midBands.length < 2) throw new Error(`${id}: only ${midBands.length} middle bands (need 2+)`);

  // IDLE / WALK / ATTACK strips all share a unified per-character height so the
  // engine can swap textures on one mesh without the figure visibly growing or
  // shrinking. Bottom-aligned (feet on the same baseline), top-padded.
  const idleB = midBands[0], walkB = midBands[1];
  const attackB = midBands[attackBandIdx]; // may be undefined if detection misses
  const pad = 2;
  const heightBands = [idleB, walkB];
  if (attackB) heightBands.push(attackB);
  const unifyH = Math.max(...heightBands.map(b => b.h)) + pad * 2;

  // IDLE / WALK: variable-width poses on an uneven pitch — re-pack into a clean
  // uniform-cell strip so the engine's 1/IDLE_WALK_FRAMES slicing lands exactly
  // on each pose (no drift / neighbour-bleed). See packUniformStrip.
  for (const [name, band] of [["idle", idleB], ["walk", walkB]]) {
    const packed = await packUniformStrip(src, data, W, H, band, unifyH, pad, IDLE_WALK_FRAMES);
    if (!packed) { console.warn(`  ! ${id}/${name}: no pose clusters found`); continue; }
    await sharp(packed.buf).toFile(join(outDir, `${name}.png`));
    console.log(`hero -> heroes/${id}/${name}.png  (${packed.w}x${packed.h}, ${packed.frames} frames)`);
  }

  // ATTACK: variable-width poses — re-pack the first ATTACK_FRAMES body swings
  // into a clean uniform-cell strip (see packAttackStrip / ATTACK_FRAMES).
  if (attackB) {
    const packed = await packAttackStrip(src, data, W, H, attackB, unifyH, pad);
    if (packed) {
      await sharp(packed.buf).toFile(join(outDir, "attack.png"));
      console.log(`hero -> heroes/${id}/attack.png  (${packed.w}x${packed.h}, ${packed.frames} frames)`);
    } else {
      console.warn(`  ! ${id}/attack: no body clusters found`);
    }
  }

  // Right column: row 0 = FACING DIRECTION (front/back/left/right, 4 frames).
  const rightBands = scanBands(data, W, H, RIGHT_X[0], RIGHT_X[1]);
  if (rightBands.length < 1) throw new Error(`${id}: no right-column band`);
  const facing = rightBands[0];
  const frames = findFacingFrames(data, W, H, RIGHT_X[0], RIGHT_X[1], facing.y0, facing.y1);
  if (frames.length < 2) { console.warn(`  ! ${id}: only ${frames.length} facing frames`); }
  // FRONT = index 0, BACK = index 1 (template order: front, back, left, right)
  const names = ["front", "back", "left", "right"];
  for (let i = 0; i < frames.length && i < 4; i++) {
    const f = frames[i];
    const pad = 2;
    const y0 = Math.max(0, facing.y0 - pad), y1 = Math.min(H - 1, facing.y1 + pad);
    const buf = await keyedPng(sharp(src).extract({ left: f.x0, top: y0, width: f.x1 - f.x0 + 1, height: y1 - y0 + 1 }));
    await sharp(buf).toFile(join(outDir, `${names[i]}.png`));
    console.log(`hero -> heroes/${id}/${names[i]}.png  (${f.x1 - f.x0 + 1}x${y1 - y0 + 1})`);
  }
}

async function main() {
  await mkdir(OUT, { recursive: true });
  for (const id of HEROES) {
    console.log(`\n=== ${id} ===`);
    try { await processHero(id); }
    catch (e) { console.warn(`  ! ${id} failed: ${e.message}`); }
  }
  console.log("\nDone.");
}

main().catch((e) => { console.error(e); process.exit(1); });
